---
title: Dfs0
aliases:
  - ../dfs0.html
---

A dfs0 file is also called a time series file.

Working with data from dfs0 files are conveniently done in one of two ways:

* [](`mikeio.Dataset`) - keeps EUM information (convenient if you save data to new dfs0 file)
* [](`pandas.DataFrame`) - utilize all the powerful methods of pandas


## Read Dfs0 to Dataset


```{python}
import mikeio

ds = mikeio.read("../data/da_diagnostic.dfs0")
ds
```

## From Dfs0 to pandas DataFrame

```{python}
df = ds.to_dataframe()
df.head()
```

## From pandas DataFrame to Dfs0


```{python}
import pandas as pd

df = pd.read_csv(
    "../data/co2-mm-mlo.csv", parse_dates=True, index_col="Date", na_values=-99.99
)
ds = mikeio.from_pandas(df)
ds.to_dfs("mauna_loa_co2.dfs0")
```


## Accumulated datavalue type

Some dfs0 items use an accumulated data value type rather than the default instantaneous type. This is common for precipitation data and can be specified using the `data_value_type` argument of [](`mikeio.ItemInfo`).

For rainfall amounts (e.g. mm), use `StepAccumulated`:

```{python}
from mikeio import ItemInfo, EUMType

item = ItemInfo(
    "Rainfall",
    EUMType.Rainfall,
    data_value_type="StepAccumulated",
)
item
```

For precipitation rates (e.g. mm/hour), use `MeanStepBackward`:

```{python}
item = ItemInfo(
    "Precipitation",
    EUMType.Precipitation_Rate,
    data_value_type="MeanStepBackward",
)
item
```


## Dfs0 example notebooks

* [Dfs0 | Relative time](../examples/dfs0/relative_time.qmd)
* [Dfs0 | getting-started-with-mikeio](https://dhi.github.io/getting-started-with-mikeio/dfs0.html) - Course literature

