# Design philosophy


## {{< fa code >}} Easy to use

Common operations such as reading a file should only need a few lines of code.

Make extensive use of existing standard libraries for scientific computing such as numpy, matplotlib and pandas.


## {{< fa brands python >}} Familiar

MIKE IO aims to use a syntax familiar to users of scientific computing libraries such as NumPy, Pandas and xarray.

## {{< fa download >}} Easy to install

```bash
$ pip install mikeio
```

## {{< fa book >}} Easy to get started
By providing many examples to cut/paste from.

Examples are available in two forms:

* [Example notebooks](examples/index.qmd)
* [Unit tests](https://github.com/DHI/mikeio/tree/main/tests)


## {{< fa layer-group >}} Abstraction over mikecore

MIKE IO is built on top of [mikecore](https://github.com/DHI/mikecore-python), the low-level Python bindings to DHI's DFS and EUM C libraries. MIKE IO provides a high-level, user-friendly API that covers the vast majority of common data processing tasks. However, to keep the API simple and focused, some advanced or niche functionality is not exposed. If you encounter an edge case that MIKE IO doesn't support, you can use mikecore directly for full low-level access. While mikecore doesn't have formal documentation, its repository contains many examples to help you get started.

## {{< fa brands osi >}} Open Source​
MIKE IO is an open source project licensed under the [BSD-3 license](license.qmd).
The software is provided free of charge with the source code available for inspection and modification.

Contributions are welcome!

## {{< fa comments >}} Easy to collaborate
By developing MIKE IO on GitHub along with a completely open discussion, we believe that the collaboration between developers and end-users results in a useful library.

## {{< fa list-ol >}} Reproducible
By providing the historical versions of MIKE IO on PyPI it is possible to reproduce the behaviour of an older existing system, based on an older version.

**Install specific version**

```bash
pip install mikeio==1.4.0
```

## {{< fa brands github >}} Easy access to new features
Features are being added all the time, by developers at DHI in offices all around the globe as well as external contributors using MIKE IO in their work.
These new features are always available from the [main branch on GitHub](https://github.com/DHI/mikeio) and thanks to automated testing, it is always possible to verify that the tests passes before downloading a new development version.

**Install development version**

```bash
$ pip install https://github.com/DHI/mikeio/archive/main.zip
```
