name: Build documentation (don't publish)

on:
  push:
    pull_request:
      branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        
    - name: Install modelskill
      run: |
        pip install .[dev]
    
    - name: Sphinx Build
      run: |
        cd docs
        make html

    - name: Upload documentation
      uses: actions/upload-artifact@v2
      with:
        name: html
        path: docs/_build/html