name: Build documentation (don't publish)

on:
  pull_request:
      branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        
    - name: Install MIKE IO
      run: |
        pip install .[dev]
    
    - name: Build documentation
      run: |
        make docs

    - name: Upload documentation
      uses: actions/upload-artifact@v2
      with:
        name: html
        path: docs/_site/
