# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Full test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.13"]

    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/ruff-action@v2 # Fail fast if there are any linting errors
      with:
        version: 0.6.2 # consistent with pyproject.toml ?
        src: mikeio # ignore notebooks
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        
    - name: Install mikeio
      run: |
        # TODO remove after release of mikecore
        pip install https://github.com/DHI/mikecore-python/releases/download/v0.3.a0/mikecore-0.3.0a0-py3-none-any.whl
        pip install .[test]
    - name: Test with pytest
      run: |
        make test
    - name: Static type check
      run: make typecheck
    - name: Build package
      run: |
        pip install build wheel twine
        python -m build
        
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist-${{matrix.python-version}}
        path: dist/*
