name: Notebooks test

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]
    types: [review_requested, ready_for_review]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"    
    - name: Install mikeio
      run: |
        pip install .[test,notebooks]    
    - name: Test notebooks
      run: |
        pytest tests/notebooks/
