name: Performance test

on:
  workflow_dispatch:

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 5 * * 0'

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - uses: extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b # v3

    - name: Set up uv
      uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6
      with:
        enable-cache: true
    - name: Install dependencies
      run: uv sync --group test --no-dev

    - name: Test with pytest
      run: just perftest
